version: "3"

services:
  rabbitmq-container:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672

  postgres-container:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=hedwig
      - POSTGRES_PASSWORD=hedwig
      - POSTGRES_DB=hedwig

  app-container:
    image: 'hedwig-user-service:latest'
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8085:8085
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-container:5432/hedwig
      - SPRING_DATASOURCE_USERNAME=hedwig
      - SPRING_DATASOURCE_PASSWORD=hedwig
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_RABBITMQ_HOST=rabbitmq-container
    depends_on:
      - rabbitmq-container
      - postgres-container